export const CREATE_USER = "CREATE_USER";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";

export const LIST_USER = "LIST_USER";
export const SUCCESS_LIST_USER = "SUCCESS_LIST_USER";


export const DOWNLOAD_FILE_PDF_EXCEL = "DOWNLOAD_FILE_PDF_EXCEL";
export const SUCCESS_FILE_DOWNLOAD = "SUCCESS_FILE_DOWNLOAD"