# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main   # runs when you push code

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build React App'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'build'
    artifact: 'react-build'
    publishLocation: 'pipeline'
  displayName: 'Publish Artifact'
